### ISSUE TITLE
Negative hashcode

### ISSUE THREAD

**Issue by therealmonE** [therealmonE/tdf4j#5]
```java Exception in thread "main" org.joor.ReflectException: Compilation error: /io/github/therealmone/cpuemulator/parser/ProgramParserImpl.java:94: error: ';' expected
        for(int i-1290479728 = 0; i-1290479728 < 3; i-1290479728++) {
                 ^
/io/github/therealmone/cpuemulator/parser/ProgramParserImpl.java:94: error: not a statement
        for(int i-1290479728 = 0; i-1290479728 < 3; i-1290479728++) {
                                               ^
/io/github/therealmone/cpuemulator/parser/ProgramParserImpl.java:94: error: ')' expected
        for(int i-1290479728 = 0; i-1290479728 < 3; i-1290479728++) {
                                                  ^
/io/github/therealmone/cpuemulator/parser/ProgramParserImpl.java:94: error: not a statement
        for(int i-1290479728 = 0; i-1290479728 < 3; i-1290479728++) {
                                                     ^
/io/github/therealmone/cpuemulator/parser/ProgramParserImpl.java:94: error: ';' expected
        for(int i-1290479728 = 0; i-1290479728 < 3; i-1290479728++) {
                                                                  ^
5 errors

	at org.joor.Compile.compile(Compile.java:97)
	at org.joor.Reflect.compile(Reflect.java:102)
	at org.joor.Reflect.compile(Reflect.java:77)
	at io.github.tdf4j.parser.ParserMetaInformation.compile(ParserMetaInformation.java:44)
	at io.github.therealmone.cpuemulator.parser.Interpreter.<init>(Interpreter.java:25)
	at io.github.therealmone.cpuemulator.Main.loadProgramInMemory(Main.java:24)
	at io.github.therealmone.cpuemulator.Main.main(Main.java:14) ```

**Comment by therealmonE** [comment]
Баг может появиться при создании Repetition элемента: 
```java prod("prod").is(repetition(t("A"), 3))```
Элемент генерируется в fori цикл, название которой состоит из хеш-кода этого элемента.
Если хеш отрицательный, код не компилируется.
